apiVersion: v1
kind: Namespace
metadata:
  name: funpod-dev

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: funpod
  namespace: funpod-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: funpod
  template:
    metadata:
      labels:
        app: funpod
    spec:
      containers:
      - name: funpod
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi

---

apiVersion: v1
kind: Service
metadata:
  name: funpod
  namespace: funpod-dev
spec:
  selector:
    app: funpod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
